### ISSUE TITLE
Redundant Masks?

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/BOSL2#1106]
The ang parameter in rounding_angled_edge_mask() defaults to 90°.  Doesn't that make rounding_edge_mask() redundant?

Should rounding_edge_mask() be dropped and rounding_angled_edge_mask() be renamed?

Same for rounding_corner_mask().

**Comment by revarbat** [comment]
This is a reasonable idea.

**Comment by adrianVmariano** [comment]
The actual shapes produced are different.  Does it matter?  For some reason rounding_angled_edge_mask makes a shape that rounds on two sides.  

This mask shape might also be used to create a fillet (that is, added to the model instead of removed) in which case the double-sided one would be bad.

**Comment by RAMilewski** [comment]
For the rounding corner masks, the orientation is different as well.  

In example 2, rounding_corner_mask() is used with corner_mask().  To do the same with rounding_angled_corner_mask() you need to add an xrot(180) between the two.

**Comment by adrianVmariano** [comment]
So does this mean we should leave things alone instead of merging the masks?
