### ISSUE TITLE
Add SynTags and check Topics and See Also

### ISSUE THREAD

**Issue by adrianVmariano** [BelfrySCAD/BOSL2#1160]
Here's a checklist for the SynTags and double checking Topics and See Also.  I've started it blank---some files are done already, I think.

- [x] affine.scad
- [x] attachments.scad
- [x] ball\_bearings.scad
- [x] beziers.scad
- [x] bottlecaps.scad
- [x] builtins.scad
- [x] color.scad
- [x] comparisons.scad
- [x] constants.scad
- [x] coords.scad
- [x] cubetruss.scad
- [x] distributors.scad
- [x] drawing.scad
- [x] fnliterals.scad
- [x] gears.scad
- [x] geometry.scad
- [x] hinges.scad
- [x] joiners.scad
- [x] linalg.scad
- [x] linear\_bearings.scad
- [x] lists.scad
- [x] masks2d.scad
- [x] masks3d.scad
- [x] math.scad
- [x] modular\_hose.scad
- [x] mutators.scad
- [x] nema\_steppers.scad
- [x] partitions.scad
- [x] paths.scad
- [x] polyhedra.scad
- [x] regions.scad
- [x] rounding.scad
- [x] screw\_drive.scad
- [x] screws.scad
- [x] shapes2d.scad
- [x] shapes3d.scad
- [x] skin.scad
- [x] sliders.scad
- [x] strings.scad
- [x] structs.scad
- [x] threading.scad
- [x] transforms.scad
- [x] trigonometry.scad
- [x] tripod\_mounts.scad
- [x] turtle3d.scad
- [x] utility.scad
- [x] vectors.scad
- [x] version.scad
- [x] vnf.scad
- [x] walls.scad
- [x] wiring.scad

**Comment by revarbat** [comment]
Completed.
