### ISSUE TITLE
[BUG]gears.scad worm_gear fails when adding shaft diameter

### ISSUE THREAD

**Issue by pwclay** [BelfrySCAD/BOSL2#1201]
**Describe the bug**

creating a worm gear fails with the error [WARNING: variable l not specified as parameter in file libraries/BOSL2/gears.scad, line 1260] when adding shaft_diam variable

**Code To Reproduce Bug**
worm_gear(mod=.33, teeth=150, worm_diam=6, worm_starts=1); works
worm_gear(mod=.33, teeth=150, worm_diam=6, worm_starts=1,shaft_diam=4); fails

**Additional context**
OpenSCAD Version: 2021.01
Other libraries used: None

Changing gears.scad line 1260 from:
 cylinder(d=shaft_diam, l=worm_diam, center=true);
to
 cylinder(d=shaft_diam, h=worm_diam, center=true);

Sorry, I am a noob on github & openscad, apologies if this is not the best way to raise this.

**Comment by adrianVmariano** [comment]
This is the right place to post this.  The gears code is undergoing massive revisions right now because a bunch of things were fundamentally incorrect, so this might not be fixed immediately.  You can make a shaft yourself by differencing a cylinder.
