### ISSUE TITLE
[BUG] Backlash reversed for internal gears

### ISSUE THREAD

**Issue by typetetris** [BelfrySCAD/BOSL2#1243]
**Describe the bug**

Backlash on ring_gear decreases the gap between an spur_gear and the ring_gear instead of
increasing it.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>;
include <BOSL2/gears.scad>;

$fn=128;

gd = gear_dist(teeth1 = 20, teeth2 = 50, internal2 = true, mod = 2);

translate([0,gd,0]) spur_gear(teeth = 20, mod = 2);
ring_gear(teeth = 50, backlash = 0.5, mod = 2);

translate([150,0,0]) union () {
translate([0,gd,0]) spur_gear(teeth = 20, mod = 2);
ring_gear(teeth = 50, mod = 2);
}

```

**Expected behavior**
Specifying backlash on a ring_gear should produce a gap between the ring_gear and a spur_gear.

Hopefully I didn't misunderstand backlash on ring_gears.

**Comment by adrianVmariano** [comment]
I think you have it right.  I added code to reverse the backlash for internal gears to fix this in the PR.  

Note: you should give a text description of issues you post.
