### ISSUE TITLE
[BUG] Backlash reversed in gear_dist for internal gears

### ISSUE THREAD

**Issue by typetetris** [BelfrySCAD/BOSL2#1245]
**Describe the bug**
With an internal gear `gear_dist(...)` should decrease with increasing `backlash`, but it does not.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
include <BOSL2/gears.scad>

gd = gear_dist(teeth1 = 20, teeth2 = 30,  internal1 = false, internal2 = true, backlash = 0, mod = 2);
gd_with_backlash = gear_dist(teeth1 = 20, teeth2 = 30,  internal1 = false, internal2 = true, backlash = 2, mod = 2);
assert(gd_with_backlash<gd,"with an internal gear gear_dist should decrease with increasing backlash");
```

**Expected behavior**
With an internal gear `gear_dist(...)` should decrease with increasing `backlash`, so there is a gap between
the gear and the ring.

**Comment by adrianVmariano** [comment]
Should have caught this when I fixed the other one.  Fixed in PR.
