### ISSUE TITLE
Minor documentation issue(s)[BUG]

### ISSUE THREAD

**Issue by jon-bondy** [BelfrySCAD/BOSL2#1256]
In 

https://github.com/BelfrySCAD/BOSL2/wiki/Tutorial-Attachments

search for typo ""singlke "

I am confused by the following: in the first example below the typo we find "align([RIGHT+TOP,LEFT+TOP])" which creates two instances of the prismoid.  Fair enough.  But if we skip down three examples, we find that "align(RIGHT+TOP,DOWN)" creates ONE instance rather than two.  I thought the comma in the 1st example caused the creation of multiple instances, so why does the comma in the 2nd example not do so?

**Comment by RAMilewski** [comment]
Not a bug.   Note the square brackets [ ] in the first example, that don't appear in the second.   I suspect align([RIGHT+TOP,DOWN]) produces the result you were expecting:

<img width="343" alt="Screen Shot 2023-08-18 at 10 15 59 AM" src="https://github.com/BelfrySCAD/BOSL2/assets/702294/54e07bbb-8989-4bba-a090-f2e73bda5412">

**Comment by revarbat** [comment]
PR checks are working.
