### ISSUE TITLE
[BUG] "No top level geometry to render" when merging with extruded projection

### ISSUE THREAD

**Issue by freiser77** [BelfrySCAD/BOSL2#1273]
**Describe the bug**
The following code issues the warning "No top level geometry to render" when rendered via F6:

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>;
include <BOSL2/screws.scad>;

// Alle Masse in mm

$fa = 0.25;
$fs = 1;

tol = 0.1;
diaHolder = 30;
depthHolder = 100;
wallThickness = 10;
addFixHeight = 5;
diaAddWall = 40;
screw = "M6";

union() {
  down(addFixHeight)
    linear_extrude(addFixHeight)
    projection(cut=true)
    upper_part();
  upper_part();
}

module upper_part() {
  down(addFixHeight)
    top_half(s=2*(depthHolder+2*wallThickness),z=addFixHeight)
    yrot(90)
    cyl(h=depthHolder+2*tol, d=diaHolder-2*addFixHeight, anchor=BOTTOM) {
      align(BOTTOM) 
        difference() {
          cyl(h=wallThickness, d=diaHolder+diaAddWall);
          left((diaHolder+diaAddWall)/2 -wallThickness)
            screw_hole(screw, head="flat large", length=wallThickness+2*tol, anchor=BOTTOM); 
        };
      align(TOP) cyl(h=wallThickness, d=diaHolder);
    };
}
```

**Expected behavior**
Smooth rendering like with F5, without any warning.

**Screenshots**
<img width="769" alt="Bildschirmfoto 2023-09-07 um 20 27 53" src="https://github.com/BelfrySCAD/BOSL2/assets/14125584/5b511d7c-9bd9-4d0f-a4d6-f9387531d40b">

**Additional context**
- OpenSCAD Version: 2023.03.06 (git 245205575)
- Other libraries used: BOSL2 (https://github.com/BelfrySCAD/BOSL2)
- OS: MacOs Ventura 13.5.1

**Comment by adrianVmariano** [comment]
This worked for me in OpenSCAD 23.08.20 but failed in the stable version, 2021.01 with a different error:

Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
WARNING: Projection() failed. 

I wonder if projection(cut=true) is not robust when the model has faces in the xy plane (sort of analogous to the problem of doing intersections that share a face.)   In this case using cut=false does produce the same result and does eliminate the error.  

My initial reaction is that this is not a BOSL2 issue.

**Comment by freiser77** [comment]
@adrianVmariano : I've switched to the stable 2021.01 version and now it works with projection(cut=false). Thanks for your help.
