### ISSUE TITLE
maxz ignored by heightfield() ?

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/BOSL2#1290]
```
a016aaadfd0b)
include <BOSL2/std.scad>
include <QR.scad>

heightfield(data = image_data, size = [100,100], bottom = 0, maxz = 20);

```
![Screen Shot 2023-10-17 at 11 51 46 AM](https://github.com/BelfrySCAD/BOSL2/assets/702294/6cf88fe0-306b-456a-93ed-db082abed90a)

image_data in QR.scad created by img2scad.py using a monochrome png of a QR code.

**Comment by adrianVmariano** [comment]
Looks like maxz only works for function inputs and not list inputs, for some reason.
