### ISSUE TITLE
Wrong foldangle in apply_folding_hinges_and_snaps() wiki example.

### ISSUE THREAD

**Issue by mizahnyx** [BelfrySCAD/BOSL2#1307]
In the `hinges.scad` wiki example for `apply_folding_hinges_and_snaps()`, the parameter foldangle is wrong, it should be 70.53 that is approximately the value of the dihedral angle of a tetrahedron. I verified it by generating and 3d printing the solid.

**Comment by adrianVmariano** [comment]
Yeah, this is right.  The angle in there is the angle between an edge and a face.  The correct angle is acos(1/3)
