### ISSUE TITLE
Creating a bowl-shaped patch from a path

### ISSUE THREAD

**Issue by s-leroux** [BelfrySCAD/BOSL2#1328]
I have previous experience in using vanilla OpenSCAD to create very basic parts, but I am new to BOSL2. I read the docs on the wiki; the library is very impressive.

I am restoring a Japy Message typewriter. It does not have much value except a sentimental one. It is a 1963 typewriter, used by my mum in her first job up to the early 70s when I was born. I try to model a key cap to create replacement parts, as many were damaged by decades of storage.

![20231211_111442](https://github.com/BelfrySCAD/BOSL2/assets/1678974/d1d7b700-bcbf-4ae3-ae32-2657c557d0cc)
![20231211_111525](https://github.com/BelfrySCAD/BOSL2/assets/1678974/87bd47e7-b314-40ee-bbde-6a2c423a6111)

I managed to create the overall shape of the key cap using smooth paths around trapezoids.  However, I have no idea how to model the top of the caps. The frame is planar, but the inside is bowl-shaped. I imagine creating a Bezier patch from the path and shifting down the inner control points. But I can't see how to achieve that. Unless there is a different approach to the problem?

![Screenshot from 2023-12-11 11 24 32](https://github.com/BelfrySCAD/BOSL2/assets/1678974/69b68d5c-209f-4ee2-9aed-0e70979afc51)
```
include <BOSL2/std.scad>
include <BOSL2/rounding.scad>

top_width = 13;
bottom_width = 15;
keycap_height = 9;

top_face = smooth_path(
    trapezoid(w1=top_width, w2=top_width-2, h=15.5),
    closed=true);

bottom_face = smooth_path(
    trapezoid(w1=bottom_width, w2=bottom_width-2, h=15.5),
    closed=true);
    
skin(slices=0,
    profiles=[bottom_face, top_face],
    z=[0, keycap_height]);
```

**Comment by adrianVmariano** [comment]
I don't have an easy answer to this.  It looks like you don't actually want a bowl.  You want a flat recess with gently sloping sides.  You could do a recess maybe by taking your border shape, offsetting it in, and using offset_sweep to make a version that is flat on the bottom, with a rounded profile.  You then subtract that from your original.

**Comment by s-leroux** [comment]
Thanks, Adrian, for the answer. I didn't manage to use offset_sweep() for my purpose. My best solution for now was to create the "finger rest" shape as the hull() around the top face and a sphere (whose radius was empirically estimated). When I flatten the shape using zscale(), it doesn't look that bad. Maybe it is a bit too "conical" compared with the original. I wonder if this will be noticeable for a 1mm-height recess. I will probably print a prototype to validate the design.

```
module finger_rest() {
    r = 7;
    up(keycap_height+1/r/2) {
        zscale(1/r) hull() {
            linear_extrude(height=1, center=true)
                polygon(top_face);
            sphere(r);
        }
    }
}

module key() {  
    skin(slices=0,
        profiles=[bottom_face, top_face],
        z=[0, keycap_height]);
}

difference() {
    key();
    finger_rest();
}
```

**Comment by adrianVmariano** [comment]
You probably need to use offset_sweep() to chamfer or round that shape.

**Comment by adrianVmariano** [comment]
Does this issue call for any action, or can we close it?

**Comment by s-leroux** [comment]
Thanks a lot for your help with that issue.
