### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rjcarlson49** [BelfrySCAD/BOSL2#1334]
**Describe the bug**
Customizer feature does not comply with "include" definition

**Code To Reproduce Bug**
```
/*
Include this file at the end of the Customizer variables
*/

doCrossSection = "none"; // ["none", "x", "y", "z", "-x", "-y", "-z", "polar"]
radius = 0;
phi = 0;
theta = 0;

module __Customizer_Limit__ () {}  // This actually works

_CS();

module _CS() {
    if (doCrossSection == "none") { 
        d = echo("none");
        assembly();
    } else if (doCrossSection == "polar") {
        d = echo("polar");
        crossSection(r = radius, theta = theta, phi = phi)
        assembly();
    } else { 
        d = echo(doCrossSection);
        crossSection(view = doCrossSection, r = radius)
        assembly();
    }
}
```

**Expected behavior**
When I include this file I would expect the customizer limit to be honored. It is not.

Include is described thusly: include <filename> acts as if the contents of the included file were written in the including file

**Screenshots**

**Additional context**
- OpenSCAD Version: 23.12.18
- Other libraries used: crossSection is part of my own library

**Comment by RAMilewski** [comment]
The Customizer is an OpenSCAD function not part of BOSL2.    

There's another way to hide variables from the Customizer.  See https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Customizer#Creating_Tabs

**Comment by rjcarlson49** [comment]
My mistake. I'm so used to BOSL2 it's hard to separate it from OpenSCAD.
