### ISSUE TITLE
Heightfield() output fails vnf_validate()

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/BOSL2#1345]
![20x20](https://github.com/BelfrySCAD/BOSL2/assets/702294/ea296653-1eda-40f9-ba82-81127abde2e5)

Running the 20x20 pixel png above through img2scad.py generates this file:

[20x20S.txt](https://github.com/BelfrySCAD/BOSL2/files/13929994/20x20S.txt)
(I changed the extension from .scad to .txt because GitHub refuses to load .scad files here.)

```
include <BOSL2/std.scad>
include <tex/20x20S.scad>

vnf =   heightfield(custom, size = [20,20], bottom = 0, maxz = 1);
vnf_validate(vnf);
```
...results in:
![Screenshot 2024-01-13 at 4 59 46 PM](https://github.com/BelfrySCAD/BOSL2/assets/702294/1900dd25-5dfb-4503-b1e9-cd9f0355a38b)
...and the following console messages:
[validate_messages.txt](https://github.com/BelfrySCAD/BOSL2/files/13930010/validate_messages.txt)

It also appears that the rendering attempt is not symmetrical while the input png is.

**Comment by RAMilewski** [comment]
This probably argues for deprecating heightfield() and replacing it with the textured cuboid top described in the comments in #1346

**Comment by RAMilewski** [comment]
It does pass however if you set bottom < 0.   ...even by as little as -1e-12.

**Comment by RAMilewski** [comment]
After some testing it appears that the resulting heighfield is invalid if any data point exactly matches the bottom argument.  

```
include <BOSL2/std.scad>
bottom =9;
maxz = 10;
data = [
    [ 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,  ],
    [ 8, 12, 12, 12, 12, 12, 12, 12, 12, 8, ],
    [ 8, 12, 8, 8, 8, 8, 8, 8, 12, 8,  ],
    [ 8, 12, 8, 8, 8, 8, 8, 8, 12, 8,  ],
    [ 8, 12, 8, 8, 8, 9, 8, 8, 12, 8,  ],
    [ 8, 12, 8, 8, 8, 8, 8, 8, 12, 8,  ],
    [ 8, 12, 8, 8, 8, 8, 8, 8, 12, 8,  ],
    [ 8, 12, 8, 8, 8, 8, 8, 8, 12, 8,  ],
    [ 8, 12, 12, 12, 12, 12, 12, 12, 12, 8,  ],
    [ 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,  ],
   
];

vnf = heightfield(data, size = [10,10], bottom = bottom, maxz = maxz);
vnf_validate(vnf);
```
<img width="435" alt="Screenshot 2024-03-08 at 12 06 40 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/702294/48cbda2e-f4b9-4722-ad39-b8e7b5ecd5b1">

**Comment by revarbat** [comment]
First, giving a size=0.1 argument to `vnf_validate()` will make much smaller purple balls in that rendering.

Second, if you view that in Thrown Together mode, you'll see that way more than the one point at z==9 is bad.  You have the bottom set higher than the lowest datums, which makes a bad polygon.  This admittedly *should* assert an error.  But basically this is an issue of Garbage-In, Garbage Out.

<img width="523" alt="Screenshot 2024-03-13 at 5 59 56 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/970ec238-153c-4fcd-9657-179748500312">

**Comment by revarbat** [comment]
Mind you, if i were to rewrite this now, I'd have the bottom always at 0, and have two arguments that would define the minimum and maximum expected input values, and two more to define the high and low heights those would map to.

**Comment by revarbat** [comment]
Something like:
```heightfield(data/fn, minval=0, maxval=255, minz=1, maxz=10);`
