### ISSUE TITLE
[BUG] "Mixing 2D and 3D objects is not supported" error when rendering

### ISSUE THREAD

**Issue by lijon** [BelfrySCAD/BOSL2#1353]
**Describe the bug**
offset_stroke() only works in preview, but fails when rendering. The result is ignored.

**Code To Reproduce Bug**
```
box = square([100,100],center=true);
offset_stroke(box,closed=true);
```

**Additional context**
- OpenSCAD Version: version 2024.01.14 (git 158c5b94f)
- Other libraries used: none

**Comment by adrianVmariano** [comment]
Not able to reproduce.  Your code produces:

![image](https://github.com/BelfrySCAD/BOSL2/assets/26014420/71fe1a74-b670-4539-9b5e-84072c84ef29)

when I render.  Using 2024.01.03.  Did you maybe combine the 2d object out of offset_stroke with a 3d object?

**Comment by adrianVmariano** [comment]
You need to linear_extrude it first.
