### ISSUE TITLE
linear_sweep vnf textures with scale!=1 fail

### ISSUE THREAD

**Issue by adrianVmariano** [BelfrySCAD/BOSL2#1355]
The heightfield textures appear OK, but the VNF textures produce disconnected rings, and sampling of the texture looks really terrible here:

![image](https://github.com/BelfrySCAD/BOSL2/assets/26014420/76645d7b-1bae-4572-964c-8153410d7371)

`linear_sweep(hexagon(r=20), scale=15/25, texture=texture("dots", $fn=16), tex_size=[5,5], h=40, tex_samples=6);`

In comparison with scale=1:

![image](https://github.com/BelfrySCAD/BOSL2/assets/26014420/c0a8ded4-2f24-47a6-87c9-b3532c0c2ccb)

**Comment by revarbat** [comment]
What the heck is going on with those texture triangulations?

**Comment by revarbat** [comment]
Both scale= and twist= can trigger this mess.
