### ISSUE TITLE
[BUG] offset_sweep "path has repeated points"

### ISSUE THREAD

**Issue by lijon** [BelfrySCAD/BOSL2#1360]
**Code To Reproduce Bug**
```
offset_sweep(rect([4,1],rounding=0.5),h=2,top=os_circle(0.5));
```

fails with:

```
ERROR: Assertion '!approx(segment[0], segment[1])' failed: "Path has repeated points" in file libraries/BOSL2/regions.scad, line 658
```

**Expected behavior**
A 4x1x2 cuboid with fully rounded sides and top

**Additional context**
- OpenSCAD Version: 2024.01.14 (git 158c5b94f)

**Comment by adrianVmariano** [comment]
Looks like rect() is duplicating points with rounding when you completely round away a side.  

As a workaround, use deduplicate on the rect() output.

**Comment by adrianVmariano** [comment]
fix merged
