### ISSUE TITLE
Expose unique $idx for each child created by grid_copies()

### ISSUE THREAD

**Issue by alastaira** [BelfrySCAD/BOSL2#1387]
Unlike (all?) other distributors, grid_copies() currently doesn't expose an $idx index for each child.

**Describe the solution you'd like**
A unique identifier to be able to address each child object created by grid_copies, and to ensure feature parity and consistency with $idx exposed by other distributors.

**Describe alternatives you've considered**
grid_copies() does expose separate $row and $col, which can be used to derive a unique index for each child for simple aligned grids (i.e. $row*COLS + $col), but this fails when, e.g. rows have been staggered, or when the grid was created without specifying a known number of rows and columns (such as when using the "inside" region)

Thankyou!

**Comment by adrianVmariano** [comment]
So you want a linear index in no particular order for the children?

**Comment by revarbat** [comment]
`grid_copies()` has `$row=` and `$col=` instead of `$idx=`.  Do you still need `$idx=`?

**Comment by revarbat** [comment]
`$col=` should be consistent in behavior even with staggering.  However, when using a shape mask, `$row=`/`$col=` pairs that would appear outside the mask shape just won't be used.

**Comment by adrianVmariano** [comment]
He said that `$row` and `$col` aren't enough.  It's nontrivial to create an index...even within the code.

**Comment by adrianVmariano** [comment]
The module and function version of grid_copies are copy-and-paste versions of each other.  Kind of ugly.    Should be consolidated....

**Comment by adrianVmariano** [comment]
This is updated.

**Comment by alastaira** [comment]
Amazing, that is perfect. 
I must congratulate all the maintainers of this repository for being some of the most responsive developers I've ever dealt with (on Github, or anywhere else). Thankyou. x
