### ISSUE TITLE
[BUG] offset_stroke() "round" ending gives pointed ending.

### ISSUE THREAD

**Issue by lijon** [BelfrySCAD/BOSL2#1391]
**Describe the bug**

See the wiki example https://github.com/BelfrySCAD/BOSL2/wiki/rounding.scad#functionmodule-offset_stroke

The `end="round"` still gives a pointed end.

**Comment by adrianVmariano** [comment]
Which example specifically?  Everything appears OK to me.

**Comment by lijon** [comment]
![](https://github.com/BelfrySCAD/BOSL2/wiki/images/rounding/offset_stroke.png)

**Comment by adrianVmariano** [comment]
Looks like `$fn` is too small.  There used to be a bug where arc used the total number of points for a circle for its arc, no matter how short the arc.  That probably made this example work in the past without setting `$fn`.

**Comment by adrianVmariano** [comment]
Fixed this in the example.

**Comment by adrianVmariano** [comment]
It computed the number of segments on the circle I think using segs() but then put that number of segments on the arc instead of dividing by the fraction of the circle that the arc occupied.  Current version should be correct.
