### ISSUE TITLE
Partial Texturing of Objects

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/BOSL2#1403]
Currently texturing is applied over the entire surface of the object.  Setting tex_reps to [1,1] stretches the texture to fit.  This distorts surface textures created with img2scad.py.  

It would be useful to be able to specify that a texture be applied without stretching to fit.  Perhaps tex_reps[0,0] ?

This can be done now by leaving large margins in the .png file supplied to img2scad.py, however this results in painfully slow processing in most cases.

<img width="416" alt="Screenshot 2024-03-06 at 2 13 31 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/702294/55ca7526-a4cf-46e8-82ab-14a50ace304a">

**Comment by adrianVmariano** [comment]
It seems to me that processing to make this happen would be to **internally** add large margins to the texture data.  So it wouldn't help with the slow processing problem.   Could that be addressed by putting the texture only on a small section and unioning with the rest?

**Comment by RAMilewski** [comment]
I think texturing a small section and unioning the rest is probably the right answer.  Having a heightfield replacement (textured cuboid top?) would enable texturing part of the flat surfaces of prismoids, and other irregular shapes with flat surfaces.
