### ISSUE TITLE
Sparse shapes beyond wall

### ISSUE THREAD

**Issue by jdanders** [BelfrySCAD/BOSL2#1416]
**Is your feature request related to a problem? Please describe.**
I love the strength and efficiency of the sparse wall, but not everything I do is oriented as a wall. Usually I start my design using cuboids and then realize I am wasting too much material and convert them to sparse walls. It drives me crazy to get the orientation and parameters right in the conversion from
```
cuboid([10,20,30]);
```
to 
```
sparse_wall(h=10, l=20, thick=30);
```
Usually the holes end up the wrong direction, then all my anchors and positions get messed up when I try to tweak orientation of the wall.

**Describe the solution you'd like**
At this point, I'd like to see a sparse cuboid, but if it makes sense, this could be expanded to other 3d shapes. A sparse_cuboid takes the same parameters as a cuboid, but adds the cutouts of the sparse_wall and puts the cutouts in the right orientation.

**Describe alternatives you've considered**
Here's my lame version of a sparse cuboid. It assumes the holes should align with the shortest dimension. A more elegant version might have a parameter that chooses hole orientation. I would love it if all the features of cuboids were available, like rounding.

**Example Code**
```
include <BOSL2/std.scad>
include <BOSL2/walls.scad>
module sparse_cuboid(size, maxang=30, strut=5, max_bridge=20, anchor=CENTER, spin=0, orient=UP) {
  if (size[0] <= size[1] && size[0] <= size[2]) // x skinny
    attachable(anchor=anchor, spin=spin, orient=orient, size=size) {
      sparse_wall(h=size[2], l=size[1], thick=size[0], maxang=maxang, strut=strut,
                  max_bridge=max_bridge);
      children();
    }
  else if (size[1] <= size[0] && size[1] <= size[2]) // y skinny
    attachable(anchor=anchor, spin=spin, orient=orient, size=size) {
      zrot(90) sparse_wall(h=size[2], l=size[0], thick=size[1], maxang=maxang, strut=strut,
                           max_bridge=max_bridge);
      children();
    }
  else if (size[2] <= size[0] && size[2] <= size[1]) // z skinny
    attachable(anchor=anchor, spin=spin, orient=orient, size=size) {
      xrot(90) zrot(90) sparse_wall(h=size[0], l=size[1], thick=size[2], maxang=maxang, strut=strut,
                           max_bridge=max_bridge);
      children();
    }
  else echo("Failed sparse cuboid");
}

```

Here's what three cuboids look like when converted to sparse_wall.
![image](https://github.com/BelfrySCAD/BOSL2/assets/15146675/ccb58789-4c16-4db7-b317-cec65da4bc09)

Here's what I would like it to look like:
![image](https://github.com/BelfrySCAD/BOSL2/assets/15146675/5a4fa9f7-db0f-4c34-9f81-63c3ec650c2c)

```
sparse_cuboid([10,20,30], strut=1);
fwd(30) sparse_cuboid([30,20,10], strut=1);
fwd(60) sparse_cuboid([20,10,30], strut=1);
```

Yes, these are the same three shapes with different orientation, but I can never figure out how to fix the orientation without major side-effects.

**Comment by revarbat** [comment]
```openscadsparse_wall(h=30, l=20, thick=10, strut=1);
```

**Comment by jdanders** [comment]
It's to use the triplet and manage the orientation of the holes (and ideally, the other cuboid parameters like rounding).

The rightmost shape in my example is the shape you reproduced, and is the shape oriented correctly for the sparse_wall. The other two shapes have suboptimal holes cut compared to my ideal results.

**Comment by revarbat** [comment]
Making cylinders sparseable along their axis is doable, but I'm unclear that spheres or arbitrary 3D shapes would be practical.

**Comment by jdanders** [comment]
Agreed on arbitrary shapes, that would be too broad. Prismoids, wedges, and octahedrons would be the other shapes from the libraries that could be practical.

I would imagine a sphere would be something like this, assuming someone smarter than me figured out how to size the holes correctly. And maybe instead of circular holes, you could do cutout so that the remaining lines were essentially the lat/long lines of the sphere.
![image](https://github.com/BelfrySCAD/BOSL2/assets/15146675/badb0567-7584-474f-ba9e-871b61d154a4)

**Comment by revarbat** [comment]
Probably would get better results with a phi spiral a la `sphere_copies()`.
```openscad
difference() {
    sphere(d=100);
    sphere(d=80);
    sphere_copies(d=100, n=50, cone_ang=180) cyl(d=10, h=20, anchor=CTR);
}
```
<img width="351" alt="Screenshot 2024-04-04 at 5 08 59 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/3be8b89e-9b72-4469-b975-d8ee3862d2b0">

**Comment by revarbat** [comment]
Wireframed icosahedrons could be useful too.
<img width="351" alt="Screenshot 2024-04-05 at 5 41 07 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/7db45329-323e-4e8a-a9cb-c60a8481da25">

**Comment by adrianVmariano** [comment]
would a "sparse_wall_mask" that could be constrained take a polygon address some of these issues?  Then it could be attached with diff() to faces of any object.

**Comment by adrianVmariano** [comment]
```
module sparse_cuboid(size, dir, strut=5, maxang=30, max_bridge=20,
    chamfer,
    rounding,
    edges=EDGES_ALL,
    except=[],
    except_edges,
    trimcorners=true,
    teardrop=false,
    anchor=CENTER, spin=0, orient=UP)
{
  dummy1=assert(is_vector(dir,3), "dir must be a 3-vector");
  count = len([for(d=dir) if (d!=0) d]);
  dummy2=assert(count==1 && len(dir)<=3, "dir must have exactly one non-zero component");
  attachable(anchor,spin,orient,size=size){
    intersection(){
      if (dir.x) 
         sparse_wall(size.z,size.y,size.x,strut=strut,maxang=maxang, max_bridge=max_bridge);
      else if (dir.y)
         zrot(90)
           sparse_wall(size.z,size.x,size.y,strut=strut,maxang=maxang, max_bridge=max_bridge);
      else
         yrot(90)
           sparse_wall(size.x,size.y,size.z,strut=strut,maxang=maxang, max_bridge=max_bridge);
      cuboid(size=size, chamfer=chamfer, rounding=rounding,edges=edges, except=except, except_edges=except_edges,
             trimcorners=trimcorners, teardrop=teardrop);
    }
    children();
  }    
}  


sparse_cuboid([10,20,30], strut=1, dir=RIGHT, rounding=3);
fwd(30) sparse_cuboid([30,20,10], strut=1, dir=UP, chamfer=1);
fwd(60) sparse_cuboid([20,10,30], strut=1, dir=FWD);
```

So something like the above?  Seems like you can get into trouble with roundings.  And also what you really want is for all the bracing to be rounded as well, which unlike the above, is nontrivial.

**Comment by RAMilewski** [comment]
I agree with jdanders comment "but I can never figure out how to fix the orientation without major side-effects", and in my case at least, it applies in other parts of BOSL2.  (e.g. linear_sweep()). Hence our discussion recently on Gitter about having a "reset" for the reference frame.

**Comment by adrianVmariano** [comment]
If you've built a model with objects that have children and change the orientation of an object it will screw up everything downstream.  But a "reset" will only help if the object in question has enough symmetry that it's anchors don't change when you change the orientation.  Otherwise you'll have trouble with positioning.
