### ISSUE TITLE
Add a preview_only argument to ruler() ?

### ISSUE THREAD

**Issue by RAMilewski** [BelfrySCAD/BOSL2#1420]
What about adding a preview_only argument to ruler which defaults to true?

If preview_only is false the ruler will render with F6.

**Comment by adrianVmariano** [comment]
Maybe it should be a `render=` arg that defaults to true (status quo) and can be set to false to prevent the ruler from rendering?

**Comment by adrianVmariano** [comment]
Hmmm.  Good point.  So maybe it should just always be preview only.

**Comment by adrianVmariano** [comment]
implemented in PR
