### ISSUE TITLE
Rounded  trapezoid

### ISSUE THREAD

**Issue by sonichy** [BelfrySCAD/BOSL2#1422]
![圆角梯形](https://github.com/BelfrySCAD/BOSL2/assets/16402249/bb91eb75-d1f8-4927-b832-b7c8dc122c9f)

**Comment by revarbat** [comment]
```openscadinclude <BOSL2/std.scad>
include <BOSL2/rounding.scad>
path = round_corners(trapezoid(w1=50, w2=70, h=50), r=10, closed=true);
polygon(path);
```

**Comment by revarbat** [comment]
Actually, I forgot that trapezoid already has rounding available.
```openscad
include <BOSL2/std.scad>
trapezoid(w1=50, w2=70, h=50, rounding=10);
```

**Comment by revarbat** [comment]
And if you need to specify a different rounding per corner, you can give the rounding= a list of four radii, for quadrants I, II, III, and IV, in order.  (X+Y+, X-Y+, X-Y-, X+,Y-, respectively.)

```openscad
include <BOSL2/std.scad>
trapezoid(w1=50, w2=70, h=50, rounding=[5, 10, 15, 20]);
```

<img width="551" alt="Screenshot 2024-04-26 at 9 31 31 AM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/3a8f04b7-4da4-4416-8d8b-baa91ba496d3">
