### ISSUE TITLE
[BUG] spiral_sweep lead_in does not work as expected

### ISSUE THREAD

**Issue by pipatron** [BelfrySCAD/BOSL2#1440]
In `spiral_sweep()`, `lead_in2` does nothing and `lead_in1` works as the plain `lead_in` argument:

````
spiral_sweep(rect(5),30,10,2,lead_in=5);
spiral_sweep(rect(5),30,10,2,lead_in1=5);
spiral_sweep(rect(5),30,10,2,lead_in2=5);
````

lead_in=5|lead_in1=5|lead_in2=5
:------:|:------:|:--------:
![lead_in=5](https://github.com/BelfrySCAD/BOSL2/assets/14086495/3535e852-9b89-4d04-92c9-8869d2e62196)|![lead_in1=5](https://github.com/BelfrySCAD/BOSL2/assets/14086495/60c9eea6-e66f-46b0-a54a-b3a4a467642d)|![lead_in2=5](https://github.com/BelfrySCAD/BOSL2/assets/14086495/4005e53e-a840-4901-85da-a7601e85d19d)

I get different breakage with `lead_in_ang`:

````
spiral_sweep(rect(5),30,10,2,lead_in_ang=20);
spiral_sweep(rect(5),30,10,2,lead_in_ang1=20);
spiral_sweep(rect(5),30,10,2,lead_in_ang2=20);
````
lead_in_ang=20|lead_in_ang1=20|lead_in_ang2=20
:------:|:------:|:--------:
![lead_in_ang=20](https://github.com/BelfrySCAD/BOSL2/assets/14086495/640e1072-c766-4140-bf85-f9b1e1f05bba)|![lead_in_ang1=20](https://github.com/BelfrySCAD/BOSL2/assets/14086495/fb506f95-81e4-43f7-b3a7-049dcc702ce5)|![lead_in_ang2=20](https://github.com/BelfrySCAD/BOSL2/assets/14086495/10c285d3-39af-42ae-bee7-c0b75289d634)

The missing render comes with this error message:

>ERROR: Assertion '(is_num(v) || is_vector(v))' failed: "Invalid scale" in file ../../openscad/lib/BOSL2/transforms.scad, line 822
TRACE: called by 'scale' in file ../../openscad/lib/BOSL2/skin.scad, line 1311
TRACE: called by 'spiral_sweep' in file ../../openscad/lib/BOSL2/skin.scad, line 1334
TRACE: assignment to 'vnf' in file ../../openscad/lib/BOSL2/skin.scad, line 1334
TRACE: called by 'spiral_sweep' in file old_headphone_inlet.scad, line 6

**Comment by adrianVmariano** [comment]
I think I have this fixed in the PR.
