### ISSUE TITLE
[BUG] inconsistency with cylindrical_extrude

### ISSUE THREAD

**Issue by antch** [BelfrySCAD/BOSL2#1444]
**Describe the bug**
It doesn't appear possible to produce a tube using a rectangle with dimensions consistent with the desired cylinder. There is a sizable gap and the ends of the rectangle do not meet.

**Code To Reproduce Bug**
```
        cylindrical_extrude(od=40,id=39)
            rect([PI*40,20]);
```

**Expected behavior**
I would expect the code to form a completely closed tube with outer diameter 40, wall thickness 1.

**Screenshots**

**Additional context**
It seems that the gap closes as `$fn` is increased, though even at `$fn=256` there is still a small gap. 
No other context other than that I am quite inexperienced with modelling so this could easily be a PEBKAC issue...
- OpenSCAD Version: 2021.01
- Other libraries used: None

**Comment by adrianVmariano** [comment]
There was an off-by-one error in constructing the facets.  Fixed in the PR.
