### ISSUE TITLE
SIGSEGV crash on a simple program

### ISSUE THREAD

**Issue by bobblkabb** [BelfrySCAD/BOSL2#1448]
**Describe the bug**
openSCAD crashes after opening a certain program. User interface appears for a moment, maybe a 2-3 seconds.

Started from terminal:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
fish: Job 1, './gearlever_openscad_2b7bbd.app…' terminated by signal SIGSEGV (Address range error)
```
(Second line appears on crash)

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
include <BOSL2/rounding.scad>

$fn = 50;

difference() {
	rotate_extrude(angle=21)
	translate([55, 0, 0])
	rotate(a = [0, 180, 0])
	stroke(smooth_path(square([5,25]), closed=true, splinesteps=100), width=1.5);
	translate([47,-3,1.5])
	rotate(a = [0, 0, 12])
	cube([5, 23, 22]);
}
```

**Expected behavior**
Leave openSCAD and its program open to edit.

**Additional context**
- OpenSCAD Version: 2024.06.25.ai19682 (git d4c36aa2b)
- Running on openSUSE Tumbleweed, hyprland
- Never happened before and the program used to work a few weeks ago
-  also tried with latest BOSL2 from today

**Comment by adrianVmariano** [comment]
If OpenSCAD crashes that is not a BOSL2 bug.  You need to post this on the OpenSCAD github.
