### ISSUE TITLE
[BUG] Parser Error on structs.scad when trying to run: `struct_set`

### ISSUE THREAD

**Issue by stiggy87** [BelfrySCAD/BOSL2#1456]
**Describe the bug**
When trying to include the `screws.scad` and create a `screw()` or a standard `struct` get the following error:

```
Parsing design (AST generation)...
[ERROR: Parser error: syntax error in file structs.scad, line 48](.../OpenSCAD/libraries/BOSL2/structs.scad)
Execution aborted
```

**Code To Reproduce Bug**
```
#include <BOSL2/std.scad>
#include <BOSL2/structs.scad>

$fn=32;

str = struct_set(struct, "answer", 42);
```

**Expected behavior**
It should not be throwing an error.

**Screenshots**
N/A

**Additional context**
- OpenSCAD Version: [OpenSCAD](https://www.openscad.org/) version 2021.01
- Other libraries used: None.

**Comment by adrianVmariano** [comment]
The parse error is that you put in those '#' characters.  OpenSCAD isn't C.  

Without then you get the error that "struct" is unknown, which is what should happen.

**Comment by stiggy87** [comment]
Thanks! It worked with just one include, so not sure why it wasn't throwing the error earlier. Closing as not a bug.
