### ISSUE TITLE
[BUG] planetary_gears() Documentation error

### ISSUE THREAD

**Issue by dan-p3rry** [BelfrySCAD/BOSL2#1470]
**Describe the bug**
The description of sun_ring and ring_sun should be swapped as far as which one is >1 and <1.  (The documentation sounds correct, but I have to set sun_ring=6 to get ring gear 6x the sun gear.)  
Also in this section, not exactly an error, the variables ring_carrier, sun_carrier, etc are inconsistent with the text, where the term "planet" is used. 

Thanks a lot for these gear functions.  I was really beating my head trying to figure this stuff out.  Turns out I was close, but not converging.

**Comment by adrianVmariano** [comment]
Gears are remarkably complex and subtle.  Are you saying that when you set sun_ring=6 you actually get a sun/ring ratio of 1/6?  Because that sounds like an implementation error.

**Comment by dan-p3rry** [comment]
No, I am saying that sun_ring=6 works, but the documentation says:  set
sun/ring ratio to this value in a sun driven system, *must have absolute
value smaller than 1*

That bold text should say "must have absolute value greater than 1".
 Setting the value to less than one causes an error in the console.

(I would argue that the arguments sun_ring and ring_sun are named
incorrectly (should be swapped), because the sun is always smaller than the
ring, but fixing that would break someone's code if they updated BOSL2.)

Dan

**Comment by dan-p3rry** [comment]
Re-reading your response, yes you are correct that setting sun_ring = 6
actually generates sun/ring ratio of 1/6.
Dan

**Comment by adrianVmariano** [comment]
That is a bug then and will need to be fixed.

**Comment by adrianVmariano** [comment]
I investigated more and it appears to me that setting sun_ring=6 produces the specified transmission ratio that the sun gear rotates six times for every single rotation of the ring gear.

**Comment by dan-p3rry** [comment]
Ok, so we are back to just the documentation error then.

**Comment by adrianVmariano** [comment]
Yeah, I have corrected the docs and also clarified that "ratio" means "transmission ratio".

**Comment by dan-p3rry** [comment]
Thanks for the fix
