### ISSUE TITLE
ball_bearings.scad, can we have a "rounding" argument?

### ISSUE THREAD

**Issue by dan-p3rry** [BelfrySCAD/BOSL2#1476]
Ball bearings have rounded edges on both the OD edges and ID edges.  Can we have the option to specify the rounding value?
According to the ball bearings spec sheets I looked at today, the interior and exterior rounding is always the same, so a single value should be adequate.

Thanks!

**Comment by adrianVmariano** [comment]
So you're asking for fillets at the bottom of the race (2 edges) and roundovers on the top?  Do we have any plausible defaults?

**Comment by dan-p3rry** [comment]
I'm asking for round-overs on ID and OD edges. In the specs I reviewed this
morning, the roundover varied depending on mfr and bearing size, so I would
not suggest using a default value.

**Comment by adrianVmariano** [comment]
So as I see it, the ball bearing has 8 circular edges, 4 on the top and 4 on the bottom.   It **appears** from looking at a McMaster diagram that all 8 are rounded or maybe chamfered.  In the case of the flange there is a 9th edge.  (In the shielded case it looks like only 4 edges.)  

Are you asking that only **some** of these edges get treated?

**Comment by dan-p3rry** [comment]
I pulled this out of NSK bearing catalog
<https://www.nsk.com/content/dam/nsk/common/catalogs/ctrgPdf/bearings/e1103b.pdf>,
page 176:  They only specify the two radii (assuming left-right symmetry),
and this is what I was looking for.  I guess the other two edges you're
referring to are at the opening where the seal will be located?   As you
can see in the table, the value varies by bearing size.

To be honest, this is a low priority for me.  If you want to decline this
enhancement request, I won't be disappointed.  If I really need the radii,
I know how to do it using cyl() with rounding argument.
Regards,
Dan


[image: image.png]

**Comment by adrianVmariano** [comment]
So if I understand that drawing then all 8 edges get the "r" rounding?   And in principle that rounding radius should get added to the dimensional tables for the bearings.

**Comment by adrianVmariano** [comment]
What happens to the flange for rounding?

**Comment by dan-p3rry** [comment]
The obvious (from p197 of the same doc):
[image: image.png]

**Comment by adrianVmariano** [comment]
Weird how the flange has a concave circular rounding instead of a fillet.  Is it supposed to snap onto something?

**Comment by dan-p3rry** [comment]
Since there is no spec/dimension associated with that undercut, it couldn't
be reliably used mechanically.  I believe it's a byproduct of the metal
forming.  I have a flanged bearing down in the garage and I never noticed
the undercut.
Dan

**Comment by adrianVmariano** [comment]
This has been open for a while and I'm not feeling motivated to go modify Revar's code to add it.  So I'm going to pass this off to him to either implement or decline to implement.  @revarbat what do you think?

**Comment by dan-p3rry** [comment]
Yes, that's fine. The rounding isn't for printing,  it's more for accuracy
when difference'ing.

Thanks & regards,
Dan

**Comment by amatulic** [comment]
Looking at the spec sheet @dan-p3rry referenced, I see I did it wrong. On the outer ring, only the outer edge is rounded, not the inner edge where the race is. And the inner hole is also rounded. It would be more like this:
![image](https://github.com/user-attachments/assets/dbc10d82-5a74-420a-89ff-7d38f63dcec2)

**Comment by amatulic** [comment]
With a flange, that spec document also shows one edge of the flange has rounding:

![image](https://github.com/user-attachments/assets/9afd886d-223c-49d5-8b36-e3d41d368b90)

It works the same way with a shield too.

**Comment by adrianVmariano** [comment]
If @dan-p3rry says you got it right then raise the PR.  But I think change `edge_r` to just `rounding` which is more consistent with other modules in the library.

**Comment by amatulic** [comment]
Done, changed `edge_r` to `rounding`. @dan-p3rry do the most recent screenshots look OK to you? It's one additional parameter, as you requested.

**Comment by dan-p3rry** [comment]
Looks good to me, thanks!
