### ISSUE TITLE
$slop documentation - material dependent

### ISSUE THREAD

**Issue by rob-miller** [BelfrySCAD/BOSL2#1485]
It seems worth noting in the writeup of the `$slop` value that it is / can be material dependent.  

I get 0, 0.1, and 0.15 for PETG-CF, PETG, and PLA respectively on a Prusa XL (FDM/FFF printer).

![IMG_5734](https://github.com/user-attachments/assets/7746c8d1-a425-4435-9171-c3ad535348cc)

**Comment by adrianVmariano** [comment]
Added a note about this which is in the latest PR.
