### ISSUE TITLE
[BUG] egg error when using argument D

### ISSUE THREAD

**Issue by gooostaw** [BelfrySCAD/BOSL2#1490]
**Describe the bug**
The egg function doesn't work if I use the D argument instead of R.

**Code To Reproduce Bug**
```
include <BOSL2/std.scad>
egg(78,d1=50,d2 = 25, D = 100);
```

**Additional context**
shapes2d.scad line 1475
```
D = get_radius(r1=R, d1=D)
```
should be changed to
```
R = get_radius(r1=R, d1=D)
```
am I right? ;)

**Comment by adrianVmariano** [comment]
You're sorta right.  There's a second problem.   I think it works in the PR.
