### ISSUE TITLE
[BUG] error in documentation of list_head function

### ISSUE THREAD

**Issue by MethylBromide** [BelfrySCAD/BOSL2#1511]
**Describe the bug**
Refer to wiki page https://github.com/BelfrySCAD/BOSL2/wiki/lists.scad#function-list_head

A line in the sample code for the list_head function reads as follows:

`hlist3 = list_head(["foo", "bar", "baz"], 2);  // Returns: ["foo","bar"]`

**Expected behavior**
The actual return value of this call is **["foo", "bar", "baz"]**, so the documentation is incorrect.
I suggest changing the second argument to 1 rather than 2. This will make the expected value correct.

**Comment by adrianVmariano** [comment]
I'll change the second arg to 1 as suggested.
