### ISSUE TITLE
more rounding flexibility for prismoid

### ISSUE THREAD

**Issue by adrianVmariano** [BelfrySCAD/BOSL2#41]
I needed to round some but not all of the edges of a prismoid...but also some top edges.  I ended up having to intersection with a cuboid to round the top and then union with an extra prismoid to unround the edges I didn't want rounded.  More flexibility (as with cuboid) would be nice.

**Comment by revarbat** [comment]
Making `prismoid()` handle rounding and chamfering is doable, but rather complex.

**Comment by adrianVmariano** [comment]
Doable but complex is why you put it into the library....

**Comment by revarbat** [comment]
I was able to implement `prismoid()` rounding and chamfering for individual vertical(ish) edges, but I haven't yet worked out a way to do top or bottom edge tweaking in a reasonable way.  f3c69eb673f48c603992ff4aa4238555698331c5

**Comment by revarbat** [comment]
Most of my problems here stem from how to make corners that allow various sized chamfers, round-overs, and unrounded edges to meet.

**Comment by adrianVmariano** [comment]
Are these problems addressed at all by rounded_prism?

**Comment by revarbat** [comment]
Maybe.  I don't see why it couldn't do that.

**Comment by revarbat** [comment]
This is more complicated than I'm inclined to implement for the initial BOSL2 release.

**Comment by revarbat** [comment]
Implementing this with `rounded_prism()` will need rounding.scad to be promoted into std.scad.

**Comment by adrianVmariano** [comment]
Does the existence of rounded_prism() mean that we just don't need more rounding for prismoid?  Users should just use rounded_prism instead?

**Comment by revarbat** [comment]
>Does the existence of rounded_prism() mean that we just don't need more rounding for prismoid? Users should just use rounded_prism instead?

I am inclined to agree.

**Comment by adrianVmariano** [comment]
One consideration before closing this:  if a user wants to round *some* of the TOP edges of a prismoid, that is impossible by any means right now.  (Other than hand positioning rounding masks, I guess.)  A limitation of rounded_prism is that all top edges must have the same rounding.

**Comment by revarbat** [comment]
I think that `edge_profile()`, `edge_profile_asym()`, and `corner_profile()` handle most of the missing rounding options.

**Comment by adrianVmariano** [comment]
Ok, so how do I round the individual top edges of this prismoid?  

```
prismoid([50,30], [30,20], shift=[3,6], h=15);
```

**Comment by revarbat** [comment]
```openscad
diff()
prismoid([50,30], [30,20], shift=[3,6], h=15, rounding=[5,0,5,0]) {
    edge_profile([TOP+RIGHT, TOP+BACK], excess=10, convexity=20) {
        mask2d_roundover(r=5,mask_angle=$edge_angle);
    }
}
```
<img width="548" alt="Screenshot 2023-11-06 at 1 57 27 PM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/087222d8-3453-48c7-b0cb-690748c48422">

**Comment by revarbat** [comment]
I think it'd be good to have an example added to `prismoid()` for this.

**Comment by revarbat** [comment]
I'll add that to my catenary()/version tweaking PR.

**Comment by adrianVmariano** [comment]
I didn't know about $edge_angle.

Is there a way to round a corner?

**Comment by revarbat** [comment]
At this time, rounding off corners of a non-cubic prismoid isn't doable via attachments.  I'm not clear how to do it, actually, as the $edge_angle would be continuously transitioning between two edges, much less three edges.

**Comment by revarbat** [comment]
This has also made it clear to me that the round-over profile masks could use a cut= option in addition to it's r= argument.

**Comment by adrianVmariano** [comment]
I really like the cut= method for specifying roundovers.   For producing roundings that match at the corner you actually would need the joint= argument.  

It seems to me like with a reference to rounded_prism() and to the use of attachable masks with $edge_angle that we can close this issue.  

Is $edge_angle new?  It's not documented at all in prismoid().  Or it's not a prismoid feature but an edge_profile() feature?  Seems like not only should there be an example but actually the paragraph that discusses rounding should also mention the option of using edge_profile with $edge_angle for rounding top edges.

**Comment by adrianVmariano** [comment]
Should edge_profile() be listed under "see also"?  

Also does the above example still work with degenerate prismoids?

**Comment by revarbat** [comment]
Okay, I've implemented `cut=` and `joint=` for `mask2d_roundover()` and `mask2d_teardrop()` based on the definitions in rounding.scad.  The main thing that this points out to me is that what is actually needed is a consistent mask height, so I've implemented `h=` for those masks as well.  And since the varying angle of the inset top on the mask makes for messy `edge_profile()` masking, I've also implemented a `flat_top=` boolean argument that forces the top inset to be horizontal for `mask2d_roundover()`.  And I made that the default.

The problem:
<img width="548" alt="Screenshot 2023-11-07 at 6 10 14 AM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/0facd249-d76b-4ad3-b582-4911349475c8">

Fixed, using h= and flat_top=true:
<img width="548" alt="Screenshot 2023-11-07 at 6 11 46 AM" src="https://github.com/BelfrySCAD/BOSL2/assets/350001/31795da9-262d-460d-8dd8-ef79e4c1f389">

**Comment by adrianVmariano** [comment]
You will need the joint= arg if you want three of them meeting at a corner.  Meeting at a corner is a notable case because it's a case that cannot be done by rounded_prism().  That is, a prismoid with only 3 roundings that meet at a corner.    But it seems like joint= should also work for the above case.  Does it fail somehow?  

Regarding degenerate prismoids it seems like in principle you could round the top edge (degenerate edge) using the TOP anchor, and $edge_angle could be set appropriately for that case---as long as shift is not set.  With nonzero shift it's a mess.  You'd have to work around the fact that the TOP anchor isn't symetric wrt the edge, which seems like a kludge.
