### ISSUE TITLE
Add Tips & Tricks page

### ISSUE THREAD

**Issue by adrianVmariano** [BelfrySCAD/BOSL2#75]
Add tips and tricks to suggest how useful turtle() can be, etc.

**Comment by revarbat** [comment]
I am unclear what I would put in here, currently.  Perhaps the Show&Tell section of the Discussions forum would be a better place for this anyways.

**Comment by adrianVmariano** [comment]
Yeah, I don't know what would go here either.  The idea of a "page" that has all the tricks for BOSL2 seems absurd.  (Note: this wasn't my idea originally;  I made the issue on your behalf.)

**Comment by revarbat** [comment]
Imma close it.
