### ISSUE TITLE
non-attachable attachables?

### ISSUE THREAD

**Issue by adrianVmariano** [BelfrySCAD/BOSL2#843]
In seems like attachable() provides 4 services blended together:  positioning the object, positioning of child objects, tagged operations, and coloring.   Should we have a form of attachable for objects that cannot be repositioned and/or cannot take children----it wouldn't need to know object dimensions----but would still allow tagged operations and colors to work properly?  

Right now there are various non-attachable objects that won't work with tagging or color.

**Comment by adrianVmariano** [comment]
```
bottlecaps.scad      bottle_adapter_*()
drawing.scad         stroke(), dashed_stroke()
geometry.scad        hull_points()
mutators.scad        [various]
partitions.scad      partition()
polyhedra.scad       [non-standard]
rounding.scad        convex_offset_extrude(), bent_cutout_mask()
screw_drive.scad     torx_mask2d(), robertson_mask()
screws.scad          screw_head()
shapes2d.scad        text()
shapes3d.scad        text3d()
wiring.scad          wire_bundle()
vnf.scad             vnf_wireframe()
```

**Comment by revarbat** [comment]
It's now possible to have a Null/Point attachment geometry where you pass no geometry args (`r=`, `size=`, etc) to `attachable()`/`reorient()`.

**Comment by adrianVmariano** [comment]
Yeah, the reason I didn't close this is because of the list above.  I fixed hull_points and text3d but the others not yet.

**Comment by adrianVmariano** [comment]
Last ones fixed.
