### ISSUE TITLE
Check usage messages and reorder for best docs: remaining files 

### ISSUE THREAD

**Issue by adrianVmariano** [BelfrySCAD/BOSL2#854]
These files need to be checked for usage text correctness according to our latest conventions, so with indication of positional vs named args, with [ATTACHMENTS]; if appropriate, possibly check for no_children($children) if not appropriate and make a no_function() version if appropriate.  

- [x] joiners.scad
- [x] sliders.scad
- [x] linear_bearings.scad
- [x] cubetruss.scad
- [x] gears.scad
- [x] nema_steppers.scad
- [x] fnliterals.scad
- [x] metric_screws.scad

Make sure also that modules and functions are presented in a natural order for the docs.  In cubetruss should the main truss be first?   Also I think cubetruss may need a better example for the clips.  I can't tell WTF they actually do out of context.  

Also make sure all exposed functions should be exposed, especially in gears.scad and nema_steppers.scad.

**Comment by revarbat** [comment]
metric_screws.scad should be going away.
